server:
  port: 8080
  server.servlet.context-path: /springboot

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/es
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # 自动更新数据表中的字段等信息
    show-sql: true  # 日志中显示sql语句